spring:
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    prefer-ip-address: false

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true